# Django commands
runserver:
	python manage.py runserver

migrate:
	python manage.py migrate

makemigrations:
	python manage.py makemigrations

shell:
	python manage.py shell

test:
	python manage.py test

createsuperuser:
	python manage.py createsuperuser

# Shortcuts (optional)
rs: runserver
m: migrate
mm: makemigrations
sh: shell
t: test
csu: createsuperuser